<?php

namespace AppBundle\Repository;

/**
 * ContractPrivateHouseServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractPrivateHouseServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
