<?php

namespace AppBundle\Repository;

/**
 * ContractHotelPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractHotelPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
