<?php

namespace AppBundle\Repository;

/**
 * ContractPrivateHousePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractPrivateHousePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
