<?php

namespace AppBundle\Repository;

/**
 * ContractTopServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractTopServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
