<?php

namespace AppBundle\Repository;

/**
 * ReservationAdministrativeChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationAdministrativeChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
